### ISSUE TITLE
L1 

### ISSUE THREAD

**Issue by Desprogienne** [ishmandoo/MassSpecPlot#11]
I like to make your life complicated, 
in order to decrease the onset voltage of my experiment I'm using a positive L1 in positive mode instead of a negative L1, apparently the python code is not happy about as it is not showing it...

[01.OCT 24 2017 20-24.zip](https://github.com/ishmandoo/MassSpecPlot/files/1415380/01.OCT.24.2017.20-24.zip)

![l1 is not here](https://user-images.githubusercontent.com/33098630/32010636-6974dd94-b980-11e7-9635-2fe4814cc302.PNG)

**Comment by ishmandoo** [comment]
Fixed this.
