### ISSUE TITLE
Total Number of Scans

### ISSUE THREAD

**Issue by kaiservilhelm** [ishmandoo/MassSpecPlot#5]
It was previously possible to naively plug in the total number of scans in a data set for the upper bound on the scans of the animation file being created without worrying about whether the range or interval of the averaging window would conflict.  It would be nice to have this feature again.

**Comment by ishmandoo** [comment]
I'll make -1 work for scan and mass indices.

**Comment by ishmandoo** [comment]
Okay, now you can use -1 for the upper scan range bound and it will use the whole file.
